import Head from "next/head"
import { useState } from "react"
import Navbar from "../components/Navbars"
import Bio from "../components/Bio"
import Project from "../components/Projects"
import projectList from "../data/projectList"



export default function Home() {

  const [darkMode, setDarkMode] = useState(false)


  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Kevin La Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <main className="px-10 pb-16 bg-white dark:bg-gray-900 md:px-20 lg:px-40">
        <section >
          <Navbar darkMode={darkMode} setDarkMode={setDarkMode} />
          <Bio />
        </section>

        <section>
          <h2 className="pb-10 text-3xl font-bold text-center dark:text-white md:text-3xl">PROJECTS:</h2>
          <div className="grid grid-cols-1 gap-5 sm:grid-cols-2 ">
            {projectList.map(project => (
              <Project
                key={project.title}
                image={project.image}
                title={project.title}
                description={project.description}
                link={project.link}
              />
            ))}
          </div>
        </section>

      </main>
    </div>
  )
}
