import Head from "next/head";
import { useState } from "react";

import Navbar from "../components/Navbars";
import Bio from "../components/Bio";
import Project from "../components/Projects";

import chess from "../public/chess.webp";
import crud from "../public/CRUD.JPG";
import journeys from "../public/journey.JPG";
import currency from "../public/currency2.jpg";


export default function Home() {

  const [darkMode, setDarkMode] = useState(false);

  const projects = [
    {
      image: journeys,
      title: 'Circular Journeys Website',
      description: 'I led the development of the ecommerce page and added payment functionality to the website as a team project. I successfully integrated the Stripe API to provide a seamless payment experience for users.',
      link: 'https://github.com/joanacircle/circular-journeys-frontend'

    },
    {
      image: crud,
      title: 'User Management System - CRUD',
      description: 'I created a user-friendly system using Node.js that enables efficient management of user information. The system seamlessly allows for the addition, updating, and removal of users in the back-end.',
      link: 'https://github.com/chenchiaho/user-management-nodejs-CRUD'

    },
    {
      image: chess,
      title: 'Three Kindoms Chess',
      description: 'A three-player board game developed and published for Android on Google Play. The app was created using the Kotlin programming language',
      link: 'https://play.google.com/store/apps/details?id=com.kevinl.android.a3kingdomschess&hl=en_US&gl=US'
    },
    {
      image: currency,
      title: 'Quick Currency App',
      description: 'A simple currency conversion app, utilizing the MVVM architecture. I used Moshi to handle and parse JSON data from an API.',
      link: 'https://github.com/chenchiaho/QuickCurrency'
    }

  ];

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Kevin La Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <main className=" bg-white px-10 pb-16 dark:bg-gray-900 md:px-20 lg:px-40">
        <section >
          <Navbar darkMode={darkMode} setDarkMode={setDarkMode} />
          <Bio />
        </section>

        <section>
          <h2 className=" text-center text-3xl font-bold pb-10 dark:text-white md:text-3xl">PROJECTS:</h2>
          <div className="grid grid-cols-1 gap-5 sm:grid-cols-2 ">
            {projects.map(project => (
              <Project
                key={project.title}
                image={project.image}
                title={project.title}
                description={project.description}
                link={project.link}
              />
            ))}
          </div>
        </section>

      </main>
    </div>
  );
}
